# frozen_string_literal: true

require "spec_helper"

# rubocop:disable RSpec/SpecFilePathFormat
describe Tetra::KitPackage do
  # rubocop:enable RSpec/SpecFilePathFormat
  include Tetra::Mockers

  before do
    create_mock_project
  end

  after do
    delete_mock_project
  end

  # Map the instance variable generated by Tetra::Mockers to an RSpec let helper
  let(:project) { @project } # rubocop:disable RSpec/InstanceVariable
  let(:instance) { described_class.new(project) }
  let(:package_name) { instance.name }

  describe "#to_spec" do
    it "generates a specfile" do
      expect(instance.to_spec).to be_truthy

      project.from_directory do
        spec_lines = File.readlines(File.join("packages", package_name, "#{package_name}.spec"))

        expect(spec_lines).to include("Conflicts:      otherproviders(tetra-kit)\n")
        expect(spec_lines).to include("Provides:       tetra-kit\n")
      end
    end
  end
end
