name: 'GitHub Action review'

on:
  push:
    branches: [ master, devel ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ master, devel ]
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
      - uses: reviewdog/action-actionlint@3986df002cad14ceab61cbd23a9f05b2f172dfde  # v1.65.2
