name: Markdown

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
    - uses: DavidAnson/markdownlint-cli2-action@1483b1cee4844bfd4ab4337aa79449702fc6f22d  # main branch as there's no release with the fix yet

