name: Markdown

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # # v7.0.1
    - uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe  # main branch as there's no release with the fix yet

