name: Markdown

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.md'
      - '.github/workflows/markdown.yml'
      - '.markdownlint.yaml'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # # v7.0.0
    - uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe  # main branch as there's no release with the fix yet

