name: RuboCop

on:
  push:
    branches: [ devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'lib/**.rb'
      - 'spec/**.rb'
      - '**.rb'
      - '.github/workflows/rubocop.yml'
      - '.rubocop_todo.yml'
      - '.rubocop.yml'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
    - uses: ruby/setup-ruby@ca041f971d66735f3e5ff1e21cc13e2d51e7e535  # v1.233.0
      with:
        ruby-version: '3.3'
    - name: Install RuboCop via bundle
      run: bundle install
    - name: Run RuboCop
      run: |
        ruby --version
        rubocop --version
        rubocop 'bin/tetra'
        rubocop 'lib/tetra.rb'
        rubocop 'lib/tetra/'
        rubocop 'spec/spec_helper.rb'
        rubocop 'spec/lib'
        rubocop 'tetra.gemspec'
