name: Tests

on:
  push:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/data/'
      - 'lib/template/bundled'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ master, devel ]
    paths:
      - '*.gemspec'
      - '**.rb'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'bin/tetra'
      - 'spec/data/'
      - 'lib/template/bundled'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      - name: Run tests and collect coverage
        run: bundle exec rake
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
